lane :build_appstore do
  xcversion(version: "11.3")

  gym(
    scheme: "MathOMat",
    configuration: "Release",
    output_directory: "./build/app-store",
    clean: true,
    export_options: "./config/AppStoreConfiguration.plist",
    output_name: "Math-o-Mat.ipa"
  )

end

lane :build_adhoc do
  xcversion(version: "11.3")

  gym(
    scheme: "MathOMat",
    configuration: "Release",
    output_directory: "./build/ad-hoc",
    clean: true,
    export_options: "./config/AdHocConfiguration.plist",
    output_name: "Math-o-Mat.ipa"
  )

end

lane :unit_tests do
  xcversion(version: "11.3")

  run_tests(scheme: "MathOMat")

end

lane :upload_binary do
  upload_to_testflight(
    username: "lfranco@greenwave-solutions.com",
    ipa: "./build/app-store/Math-o-Mat.ipa",
    team_id: "159005"
  )

end